FROM python:3.9-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    software-properties-common \
    && rm -rf /var/lib/apt/lists/*

COPY ./scripts/streamlit/requirements.txt .
COPY ./scripts/streamlit/streamlit-app.py .

RUN pip install -r requirements.txt

EXPOSE 8501

CMD streamlit run streamlit-app.py